# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_mainshow_mustbuy_nav_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=10)),
                ('typename', models.CharField(max_length=20)),
                ('childtypenames', models.CharField(max_length=100)),
                ('typesort', models.CharField(max_length=10)),
            ],
        ),
    ]
